language: go
go:
  - 1.2
  - tip
install:
  - go get github.com/elazarl/goproxy
  - go get code.google.com/p/go.net/publicsuffix
notifications:
  email:
    recipients: parnurzeal@gmail.com
    on_success: change
    on_failure: always
